TrajectoryPlannerROS:
  meter_scoring: true
  max_vel_x: 0.4        # Giảm từ 0.5 để phù hợp với khả năng của Gazebo
  min_vel_x: 0.1        # Giữ nguyên
  max_vel_theta: 0.5    # Giảm từ 1.0 để đồng bộ tốc độ quay
  min_in_place_vel_theta: 0.2  # Giảm từ 0.4 để dễ đạt tốc độ quay tại chỗ
  acc_lim_x: 1.5        # Giảm từ 2.5 để tránh lệnh quá nhanh
  acc_lim_theta: 1.5    # Giảm từ 3.2 để đồng bộ gia tốc quay
  yaw_goal_tolerance: 0.3  # Tăng từ 0.2 để giảm sai lệch góc
  xy_goal_tolerance: 0.3   # Tăng từ 0.2 để giảm sai lệch vị trí
  latch_xy_goal_tolerance: true  # Giữ nguyên
  sim_time: 1.7         # Tăng từ 1.5 để cải thiện dự đoán quỹ đạo
  sim_granularity: 0.025  # Giữ nguyên
  path_distance_bias: 20.0  # Giảm từ 32.0 để giảm ưu tiên bám đường
  goal_distance_bias: 30.0  # Tăng từ 24.0 để ưu tiên đến đích
  obstacle_distance: 0.5  # Giữ nguyên