wheel_left1_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_left1_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

wheel_left2_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_left2_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

wheel_right1_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_right1_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

wheel_right2_joint_controller:
  type: effort_controllers/JointVelocityController
  joint: wheel_right2_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
