ekf_localization_node:
  frequency: 30
  sensor_timeout: 0.1
  two_d_mode: true

  odom0: odom         # topic từ encoder / diff_drive
  odom0_config: [true, true, false,   # x, y, z
                 false, false, true,  # roll, pitch, yaw
                 true, true, false,   # vx, vy, vz
                 false, false, true,  # vroll, vpitch, vyaw
                 false, false, false] # ax, ay, az

  imu0: imu/data
  imu0_config: [false, false, false,
                true,  true,  true,
                false, false, false,
                false, false, true,
                false, false, false]
  imu0_differential: false
  imu0_remove_gravitational_acceleration: true

  base_link_frame: base_link
  odom_frame: odom
  world_frame: map

  publish_tf: true
