global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0     # Tăng từ 1.0 -> 5.0 Hz để cập nhật bản đồ nhanh hơn khi gặp vật cản mới
  publish_frequency: 2.0    # Đẩy bản đồ ra cho move_base nhanh hơn
  resolution: 0.05          # Độ phân giải của costmap
  robot_radius: 0.25        # (thêm) bán kính robot để tự động vẽ ra biên an toàn (nếu bạn không dùng footprint)

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  static_layer:
    map_topic: /map
    subscribe_to_updates: true
    enabled: true
    static_map: true

  obstacle_layer:
    enabled: true
    observation_sources: laser_scan
    laser_scan:
      data_type: LaserScan
      topic: /scan             # Đúng tên topic laser bạn đang publish
      marking: true            # Đánh dấu vùng có vật cản
      clearing: true           # Xóa vùng khi vật cản biến mất
      obstacle_range: 3.0
      raytrace_range: 3.0
      max_obstacle_height: 2.0

  inflation_layer:
    enabled: true
    inflation_radius: 0.8       # Bán kính đệm tránh vật cản
    cost_scaling_factor: 7.0   # Độ dốc chi phí càng lớn robot càng né vật cản nhiều hơn
    track_unknown_space: false  # Không đi vào vùng chưa biết
    combination_method: 1       # (bổ sung) nếu có nhiều lớp costmap, chọn mức chi phí cao nhất
