local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer", 
     inflation_radius: 1.0,  # Bán kính của tường ảo (1m)
     cost_scaling_factor: 10.0}  # Độ mạnh của vật cản (càng lớn, càng khó đi qua)
